<a href="https://colab.research.google.com/github/lolozor/LinAl/blob/master/LinAl_2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [41]:
import random

In [54]:
def mult(a, b, result):
  for i in range(len(a)):
        for j in range(len(b[0])):
                for k in range(len(b)):
                        result[i][j] += a[i][k] * b[k][j]
  return result

In [65]:
a1 = int(input('Строк в 1 матрице: '))
b1 = int(input('Столбцов в 1 матрице: '))
a2 = int(input('Строк во 2 матрице: '))
b2 = int(input('Столбцов во 2 матрице: '))

a = [[random.randint(0,10) for i in range(a1)] for j in range(b1)]
b = [[random.randint(0,10) for k in range(a2)] for l in range(b2)]
r = np.zeros((b1,a2), dtype=int)

res = mult(a,b,r)
print(res)

Строк в 1 матрице: 4
Столбцов в 1 матрице: 3
Строк во 2 матрице: 5
Столбцов во 2 матрице: 4
[[ 93  59  88  32  19]
 [179 227 232 132  89]
 [128  70 112  44  20]]


Проверка

In [67]:
import numpy as np

print(np.array(a).dot(np.array(b)))

[[ 93  59  88  32  19]
 [179 227 232 132  89]
 [128  70 112  44  20]]
